cutadapt \
 -O \
 10 \
 -f \
 fastq \
 --match-read-wildcards \
 --times \
 1 \
 -e \
 0.1 \
 --quality-cutoff \
 6 \
 -m \
 18 \
 -o \
 SA.OE.X1A.r1.fqTrTr.fq \
 -p \
 SA.OE.X1A.r2.fqTrTr.fq \
 -A ATATAGGNNNNNAGA \
 -A AATAGCANNNNNAGA \
 -A TATAGGNNNNNAGAT \
 -A ATAGCANNNNNAGAT \
 -A ATAGGNNNNNAGATC \
 -A TAGCANNNNNAGATC \
 -A TAGGNNNNNAGATCG \
 -A AGCANNNNNAGATCG \
 -A AGGNNNNNAGATCGG \
 -A GCANNNNNAGATCGG \
 -A GGNNNNNAGATCGGA \
 -A CANNNNNAGATCGGA \
 -A GNNNNNAGATCGGAA \
 -A ANNNNNAGATCGGAA \
 -A NNNNNAGATCGGAAG \
 -A NNNNNAGATCGGAAG \
 -A NNNNAGATCGGAAGA \
 -A NNNNAGATCGGAAGA \
 -A NNNAGATCGGAAGAG \
 -A NNNAGATCGGAAGAG \
 -A NNAGATCGGAAGAGC \
 -A NNAGATCGGAAGAGC \
 -A NAGATCGGAAGAGCG \
 -A NAGATCGGAAGAGCG \
 -A AGATCGGAAGAGCGT \
 -A GATCGGAAGAGCGTC \
 -A ATCGGAAGAGCGTCG \
 -A TCGGAAGAGCGTCGT \
 -A CGGAAGAGCGTCGTG \
 -A GGAAGAGCGTCGTGT \
 SA.OE.X1A.r1.fqTr.fq \
 SA.OE.X1A.r2.fqTr.fq >  SA.OE.X1A.r1.fqTrTr.metrics
